name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: deploy
        run: |
          echo "Hello from ${{ vars.MY_ENV_NAME }}"
